# -*- mode: ruby -*-
# vi: set ft=ruby :

$common = <<SCRIPT

GREEN='\033[32m'
RC='\033[0m'

printf "%b\n" "${GREEN}***${RC} Add hosts to /etc/hosts ..."

echo '127.0.0.1       localhost' > /etc/hosts
echo '' >> /etc/hosts
echo 'ff02::1 ip6-allnodes' >> /etc/hosts
echo 'ff02::2 ip6-allrouters' >> /etc/hosts
echo '' >> /etc/hosts
echo '192.168.99.101 alma-1.homework.lab alma-1' >> /etc/hosts
echo '192.168.99.102 alma-2.homework.lab alma-2' >> /etc/hosts
echo '192.168.99.103 alma-3.homework.lab alma-3' >> /etc/hosts
echo '192.168.99.104 alma-4.homework.lab alma-4' >> /etc/hosts

SCRIPT

$dns = <<SCRIPT

GREEN='\033[32m'
RC='\033[0m'

printf "%b\n" "${GREEN}***${RC} Add DNS servers ..."

echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
echo "nameserver 1.1.1.1" | sudo tee -a /etc/resolv.conf > /dev/null

SCRIPT


Vagrant.configure("2") do |config|
    config.vm.box = "tonytech/almalinux-9-5"
    config.vm.box_version = "0.0.1"
  
    1.upto(4) do |i|
      config.vm.define "alma-#{i}" do |node|
        node.vm.network "private_network", ip: "192.168.99.10#{i}"
        node.vm.hostname = "alma-#{i}.homework.lab"
        node.vm.disk :disk, size: "5GB", name: "alma-disk-#{i}"
        node.vm.provision "shell", inline: $common
        node.vm.provision "shell", inline: $dns
      end
    end
  
end