# -*- mode: ruby -*-
# vi: set ft=ruby :

$common = <<SCRIPT

GREEN='\033[32m'
RC='\033[0m'

printf "%b\n" "${GREEN}***${RC} Add hosts to /etc/hosts ..."

for i in $(seq 1 4); do echo "192.168.99.$((100 + i))    debian-$i.homework.lab    debian-$i" | sudo tee -a /etc/hosts; done

SCRIPT

$dns = <<SCRIPT

GREEN='\033[32m'
RC='\033[0m'

printf "%b\n" "${GREEN}***${RC} Add DNS servers ..."

echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
echo "nameserver 1.1.1.1" | sudo tee -a /etc/resolv.conf > /dev/null

SCRIPT


Vagrant.configure("2") do |config|
    config.vm.box = "tonytech/debian-12-9"
    config.vm.box_version = "1.0.0"
  
    1.upto(4) do |i|
      config.vm.define "debian-#{i}" do |node|
        node.vm.network "private_network", ip: "192.168.99.10#{i}"
        node.vm.hostname = "debian-#{i}.homework.lab"
        node.vm.disk :disk, size: "5GB", name: "debian-disk-#{i}"
        node.vm.provision "shell", inline: $common
        node.vm.provision "shell", inline: $dns
      end
    end
  
end