# -*- mode: ruby -*-
# vi: set ft=ruby :

$update_python = <<SCRIPT
RC='\033[0m'
RED='\033[31m'

printf "%b\n" "${RED}***${RC} Updating Python to version 3.9 ..."

# Install Python 3.9
sudo zypper install --no-confirm python39

# Verify the change
python3 --version
SCRIPT


$system_update = <<SCRIPT
RC='\033[0m'
RED='\033[31m'

# Detect the distribution type using /etc/os-release
DTYPE="unknown"  # Default to unknown
if [ -f /etc/os-release ]; then
    . /etc/os-release
    DTYPE=$ID
fi

printf "%b\n" "${RED}***${RC} Installing distribution updates ..."

# Preconfigure postfix to suppress interactive prompts
echo "postfix postfix/mailname string vagrant.local" | sudo debconf-set-selections
echo "postfix postfix/main_mailer_type string 'No configuration'" | sudo debconf-set-selections

if [ "$DTYPE" = "debian" ]; then
    sudo apt-get update && sudo apt-get upgrade -y
elif [ "$DTYPE" = "opensuse-leap" ]; then
    sudo zypper refresh && sudo zypper update -y
elif [ "$DTYPE" = "almalinux" ]; then
    sudo dnf update -y
else
    echo "Unsupported distribution: $DTYPE"
fi

SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "tonytech/suse-leap-15-6"
    config.vm.box_version = "0.0.1"

    # Router
    config.vm.define "router" do |router|
        router.vm.hostname = "router.homework.lab"
        router.vm.network "public_network", bridge: true, ip: "192.168.88.110"
        router.vm.network "private_network", ip: "192.168.99.101"
       # router.vm.provision "shell", inline: $system_update
        router.vm.provision "shell", inline: $update_python
    end

    # Client
    config.vm.define "client" do |client|
        client.vm.hostname = "alma-client.homework.lab"
        client.vm.network "public_network", bridge: true, ip: "192.168.88.111"
        client.vm.network "private_network", ip: "192.168.99.102"
        #client.vm.provision "shell", inline: $system_update
        client.vm.provision "shell", inline: $update_python
    end

end

